server:
  port: 9999

spring:
  application:
    name: gateway-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring.cloud.gateway:
      routes:
        - id: MOVIE-MANAGEMENT-SERVICE
          uri: http://192.168.1.23:9090
          predicates:
            - Path=/api/moviemanagementservice/**
        - id: MOVIE-SERVICE
          uri: http://192.168.1.23:8084
          predicates:
            - Path=/api/movieservice/**
