version: '3.8'

services:
  postgresql-db:
    container_name: postgresql-db
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: haryharsono
      POSTGRES_USER: haryharsono
      POSTGRES_DB: haryharsono
