eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8080
spring:
  application:
    name: movie-management-service
  cloud:
    config:
      uri: http://localhost:8888
      enabled: true


